### ISSUE TITLE
_reset.scss文件的第18行font-size应该为62.5%

### ISSUE THREAD

**Issue by HydeSong** [marvin1023/sandal#1]
html {
    -ms-text-size-adjust: 100%; // 1
    -webkit-text-size-adjust: 100%; // 1
    -webkit-tap-highlight-color: transparent; // 2
    font-size: 62.5%;
    height: 100%;
}

**Comment by marvin1023** [comment]
这个不是bug，是我故意设置为那么大的，你这个就相当于10px，我设置的相当于100px。因为10px计算的时候可能会出现bug，比喻设置宽度为10rem，计算出来的是10*12px = 120px，因为webkit最小的font-size为12px。我已经把字体的设置去掉了，感觉没多大用途，谢谢！
