### ISSUE TITLE
为什么要这样写呢？

### ISSUE THREAD

**Issue by lvliang271486017** [marvin1023/sandal#6]
@mixin hidden-clip($extend: true) {
    @if $extend {
        @extend %hidden-clip;
    }
    @else {
        position: absolute;
        clip: rect(1px, 1px, 1px, 1px);
    }
}

%hidden-clip {
    @include hidden-clip(false);
}

**Comment by marvin1023** [comment]
保证如果有多个地方使用 @include 调用mixin，也可以达到 @extend 的效果
